Raman: Homework_19 is Done
eugene-okulik/dialog_tech pull request #18
Opened 2024-03-25 19:00 UTC by romakun

2024-03-26 07:33 UTC, eugene-okulik requested changes

2024-03-26 07:33 UTC, eugene-okulik commented on homework/raman_kuntsevich/homework_19/test_api.py
> +    assert all(obj_id in response_ids for obj_id in params['id']), 'Not all requested objects returned'
С точки зрения практики отправки нескольких запросов одной командой - клево. С точки зрения тестирования - не имеет особого смысла. Чем продиктован выбор именно этих id? Почему тогда уже не попробовал со всеми id, которые есть в системе? Как минимум, мы знаем, что эта АПИ поддерживает два типа id: просто число или длинная строка. Было бы лучше как раз проверить эти два варианта. Ну и в тестировании это делается с помощью parametrize.

2024-03-26 07:33 UTC, eugene-okulik commented on homework/raman_kuntsevich/homework_19/test_api.py
> +    obj_id = '13'
Почему с этим id? Ты уверен, что при следующем запуске (или через месяц/год) объект с таким id все еще будет существовать?

2024-03-26 07:33 UTC, eugene-okulik commented on homework/raman_kuntsevich/homework_19/test_api.py
> +@pytest.mark.parametrize('random_body', [None] * 3)
Здесь ты сделал parametrize, который просто говорит, что нужно 3 раза запустить тест. А нужно сделать такой parametrize, который передаст в тест 3 набора данных. Да, ты загнал себя в ловушку тем, что сделал get_random_body фикстурой. Но это могло быть просто вспомогательной функцией. Мы не тесты подкручиваем под существующие фикстуры и функции, а мы создаем такие фикстуры и функции, которыми будет удобно пользоваться в тестах.  
У тебя всё равно в каждом тесте есть строка `body = get_random_body`. Если сделать get_random_body функцией, то всё, что поменяется в тестах, это добавятся скобочки `body = get_random_body()`

2024-03-26 10:31 UTC, romakun commented on homework/raman_kuntsevich/homework_19/test_api.py
> +    obj_id = '13'
Забыл дописать =)

2024-03-26 10:32 UTC, romakun commented on homework/raman_kuntsevich/homework_19/test_api.py
> +@pytest.mark.parametrize('random_body', [None] * 3)
Да, тут намудрил. Поправлю.

2024-03-26 11:00 UTC, romakun commented on homework/raman_kuntsevich/homework_19/test_api.py
> +    assert all(obj_id in response_ids for obj_id in params['id']), 'Not all requested objects returned'
Я просто больше концентрировался на технической части. Переделал ) 
"отправки нескольких запросов одной командой" тут не совсем понял. Ведь уходит 1 запрос. Суть в том, что одним запросом можем получить выборочное количество конкретных постов

2024-03-27 08:12 UTC, eugene-okulik commented on homework/raman_kuntsevich/homework_19/test_api.py
> +    assert all(obj_id in response_ids for obj_id in params['id']), 'Not all requested objects returned'
А, точно

2024-03-27 08:44 UTC, eugene-okulik approved these changes
Намудрил много, но прикольно что разобрался с indirect.

2024-03-27 08:44 UTC, eugene-okulik commented on homework/raman_kuntsevich/homework_19/test_api.py
> +@pytest.mark.parametrize('body', [get_random_body() for _ in range(3)])
С таким parametrize ты по сути запускаешь 3 одинаковых теста. В этом нет особого смысла. Если бы это были кардинально разные данные, то клево. А так, данные, то будут похожими. Ну, разве что, повышается шанс рандомно попасть на какие-то специфические данные, которые апишка не сможет переварить.

2024-03-27 08:44 UTC, merged